Alias /quermy "C:/laragon/etc/apps/quermy/public/"

# To give access from outside, replace:
#
#   Require local
#
# with:
#
#   Require all granted
#

<Directory "C:/laragon/etc/apps/quermy/public/">
  Options Indexes FollowSymLinks MultiViews
  AllowOverride all

  Require local

</Directory>
